#! /usr/bin/env bash

SOURCE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
WHOIS="${SOURCE_DIR}/NNRI4O-NORID.whois"

if [ ! -e "${WHOIS}" ]; then
  echo '-c utf-8 NNRI4O-NORID' | nc whois.norid.no 43  > ${WHOIS}
fi

WHOIS=$(cat ${WHOIS} | grep -P 'Domains\.{5,}: ' | sed -e 's/Domains\.*: *//' | tr ' ' '\n')

# We want both IDN and not-IDN versjons of applicable domains
WHOIS_AND_IDN=$(while read D; do
  echo "$D"
  echo "$D" | idn
done <<< "$WHOIS";)

WHOIS_AND_IDN_UNIQ=$(echo "$WHOIS_AND_IDN" | sort | uniq)

# Valid chars: 
# https://www.norid.no/en/domeneregistrering/idn/idn_nyetegn/
echo -n "$WHOIS_AND_IDN_UNIQ" | \
sed -e 's/\.no$//' -e '/^no\.$/d' -e 's/\./\\./g'  | sed \
-e 's/à/\\x{E0}/g' -e 's/á/\\x{E1}/g' -e 's/ä/\\x{E4}/g' \
-e 's/å/\\x{E5}/g' -e 's/æ/\\x{E6}/g' -e 's/ç/\\x{E7}/g' \
-e 's/è/\\x{E8}/g' -e 's/é/\\x{E9}/g' -e 's/ê/\\x{EA}/g' \
-e 's/ñ/\\x{F1}/g' -e 's/ò/\\x{F2}/g' -e 's/ó/\\x{F3}/g' \
-e 's/ô/\\x{F4}/g' -e 's/ö/\\x{F6}/g' -e 's/ø/\\x{F8}/g' \
-e 's/ü/\\x{FC}/g' -e 's/č/\\x{010D}/g' -e 's/đ/\\x{0111}/g' \
-e 's/ŋ/\\x{014B}/g' -e 's/ń/\\x{0144}/g' -e 's/š/\\x{0161}/g' \
-e 's/ŧ/\\x{0167}/g' -e 's/ž/\\x{017E}/g' | LC_ALL=c sort -z | tr \
-d '\0' | tr '\n' '|'
