#! /usr/bin/env python3
import fileinput
from urllib import parse
import sys
import codecs 

repetitions = 1
if len(sys.argv) > 1:
    repetitions = int(sys.argv[1])

sys.stdin = codecs.getreader('utf8')(sys.stdin.detach(), errors='ignore')

for line in sys.stdin:
    if len(line):
        for _ in range(0,repetitions):
            line = parse.unquote(line)
        print(line.strip())
